# syntax=docker/dockerfile:1

## Build
FROM golang:1.18-buster AS build

WORKDIR /app

COPY go.mod ./
COPY go.sum ./
RUN go mod download

COPY *.go ./

RUN go build -o /mongodb-multidoc-transactions

## Deploy
FROM gcr.io/distroless/base-debian10

WORKDIR /

COPY --from=build /mongodb-multidoc-transactions /mongodb-multidoc-transactions

EXPOSE 8090

USER nonroot:nonroot

ENTRYPOINT ["/mongodb-multidoc-transactions"]